### PR TITLE
General: PEP8 corrections and cleanups

### PR DESCRIPTION
**Pull request by thopiekar**
WIP

### CODE REVIEW

**Comment by thopiekar** [comment]
Glad to hear that you like it! 😄 

Well, it is actually made by hand. I only get markers by my IDE and then I need to think how to make the code look good actually 😅 I also found mixed indentions 2 whitespaces VS 4 whitespaces. In these scenarios, I wouldn't trust any auto-formatting tool..
Well, your idea is not bad, since there is also a lot to do still.

pycodestyle allows different checks. Either check for all pep8 conventions, check only for one type (--select) or exclude some (--ignore).
I guess it would be good to stop fixing all at once now and focus on one. Here is a list of the remaining errors:
```
247     E101 indentation contains mixed spaces and tabs
763     E111 indentation is not a multiple of four
85      E114 indentation is not a multiple of four (comment)
124     E115 expected an indented block (comment)
18      E116 unexpected indentation (comment)
5876    E117 over-indented
109     E122 continuation line missing indentation or outdented
87      E124 closing bracket does not match visual indentation
6       E125 continuation line with same indent as next logical line
261     E127 continuation line over-indented for visual indent
527     E128 continuation line under-indented for visual indent
3       E129 visually indented line with same indent as next logical line
31      E131 continuation line unaligned for hanging indent
2174    E201 whitespace after '{'
568     E202 whitespace before ']'
285     E203 whitespace before ':'
187     E211 whitespace before '('
2356    E221 multiple spaces before operator
126     E222 multiple spaces after operator
537     E223 tab before operator
1       E224 tab after operator
2505    E225 missing whitespace around operator
377     E227 missing whitespace around bitwise or shift operator
45      E228 missing whitespace around modulo operator
2860    E231 missing whitespace after ','
1214    E251 unexpected spaces around keyword / parameter equals
1190    E261 at least two spaces before inline comment
211     E262 inline comment should start with '# '
644     E265 block comment should start with '# '
380     E266 too many leading '#' for block comment
16      E271 multiple spaces after keyword
1       E272 multiple spaces before keyword
6       E273 tab after keyword
776     E301 expected 1 blank line, found 0
1479    E302 expected 2 blank lines, found 0
44      E303 too many blank lines (2)
316     E305 expected 2 blank lines after class or function definition, found 1
21      E306 expected 1 blank line before a nested definition, found 0
223     E401 multiple imports on one line
163     E402 module level import not at top of file
4351    E501 line too long (81 > 79 characters)
344     E502 the backslash is redundant between brackets
435     E701 multiple statements on one line (colon)
21      E702 multiple statements on one line (semicolon)
135     E703 statement ends with a semicolon
39      E711 comparison to None should be 'if cond is None:'
2       E712 comparison to True should be 'if cond is True:' or 'if cond:'
6       E713 test for membership should be 'not in'
12      E714 test for object identity should be 'is not'
48      E721 do not compare types, use 'isinstance()'
220     E722 do not use bare 'except'
19      E731 do not assign a lambda expression, use a def
21      E741 ambiguous variable name 'l'
17122   W191 indentation contains tabs
498     W291 trailing whitespace
25      W292 no newline at end of file
589     W293 blank line contains whitespace
57      W391 blank line at end of file
4       W602 deprecated form of raising exception
56      W605 invalid escape sequence '\d'
```

**Comment by mhammond** [comment]
> I guess it would be good to stop fixing all at once now and focus on one.

Maybe as a first pass, something where `diff --ignore-all-space ...` is empty?

**Comment by mhammond** [comment]
> I wouldn't trust any auto-formatting tool..

And FTR, I absolutely would - far more than hand-formatted.

**Comment by thopiekar** [comment]
As far as I understand the info provided via --help, the "normal" run of autopep8 should make only changes as you want (`diff --ignore-all-space` == ""). As soon as you make it more aggressive, it will make more major changes to the code.

Honestly, I'm really surprised how good that tool works.

The only thing I'll do is to add "|| exit 0" to the test, to it keeps checking but overwrites the exit-code of pycodestyle for this state of work. I would put all the IDs into white- or blacklists of course, but I better invest time into making all the final changes to be fully PEP8 compatible.

@mhammond Do you agree?

**Comment by mhammond** [comment]
> @mhammond Do you agree?

Sorry for the delay here, but I'm afraid I don't understand your question.

**Comment by mhammond** [comment]
Thanks for this, but my current plan is to use `black`, which I intend landing in the next week or so, so I'll close this out.

**Pull request closed without merging**
