### PR TITLE
Implement record pointers as [in, out] method parameters of a Dispatch Interface

### LINKED ISSUE #2304: Missing support for record pointers as method parameters of a Dispatch Interface.
With a COM Dual Interface it is possible to get server side changes to record members marshaled back to the client when the type library specifies a record pointer as an [in, out] interface method parameter.

The Python [comtypes ](https://github.com/enthought/comtypes)package supports this for custom COM interfaces and the support for iDispatch was recently added with [PR#535](https://github.com/enthought/comtypes/pull/535).

Pywin32 does currently not support this and seems to pass a record parameter "by value" to the type library marshaler.
Therefore COM server side changes to record members are not marshaled back to the client and the record stays unmodified on the client side.

I tried to figure out what changes to pywin32 would be required to implement this support but am a little lost because the mechanics of the package seems to be way more complex than that of the comtypes package.

I would appreciate hints on where and how this support could be implemented.
From a first look it seems to me that the issue starts in [com/win32com/client/build.py](https://github.com/mhammond/pywin32/blob/main/com/win32com/client/build.py) line 533:
```
        if indir_vt == pythoncom.VT_PTR:
            # If it is a VT_PTR to a VT_USERDEFINED that is an IDispatch/IUnknown,
            # then it resolves to simply the object.
            # Otherwise, it becomes a ByRef of the resolved type
            # We need to drop an indirection level on pointer to user defined interfaces.
            # eg, (VT_PTR, (VT_USERDEFINED, somehandle)) needs to become VT_DISPATCH
            # only when "somehandle" is an object.
            # but (VT_PTR, (VT_USERDEFINED, otherhandle)) doesn't get the indirection dropped.
            was_user = (
                isinstance(subrepr, tuple) and subrepr[0] == pythoncom.VT_USERDEFINED
            )
            subrepr, sub_clsid, sub_doc = _ResolveType(subrepr, itypeinfo)
            if was_user and subrepr in [
                pythoncom.VT_DISPATCH,
                pythoncom.VT_UNKNOWN,
                pythoncom.VT_RECORD,
            ]:
                # Drop the VT_PTR indirection
                return subrepr, sub_clsid, sub_doc
```
However, I have currently no idea what implications this has, if C++ code would have to be changed and how much effort it would be to handle pointers to User Defined Types as COM method parameters.

### PR DESCRIPTION
**Pull request by geppi**
to get server side modifications of a record marshaled back to the client.

COM interfaces with an [in, out] method parameter of type pointer to record can get
server side changes to record fields marshaled back to the client.

The current implementation of win32com does not support this and drops
an indirection level on pointer to records, i.e. the VT_BYREF attribute from a VT_RECORD.

This pull request changes the handling of record pointers and enables server side modifications of record fields to be visible on the client side. The standard type library marshaler does marshal those server side modifications back to the COM client when the VARIANT type of a parameter in the DISPPARAMS structure is (VT_BYREF | VT_RECORD).

This pull request resolves #2304.

### CODE REVIEW

**Comment by geppi** [comment]
I was hoping to receive some feedback about what would be required to merge this PR and have in the meantime taken a look into the testing facility of this project. I discovered the sources for the C++ PyComTest server-dll and the related Python unittest files which seem to me the most appropriate place to implement a test case for this PR.

However, I've also noticed that in CI these tests are not used and that the PyCOMTest sources only contain rather old versions of Visual Studio 6.0 project files. Therefore I'm wondering if the PyComTest server-dll is still actively used locally by the maintainers of this project and if there are probably project files available for some recent version of Visual Studio?

Another possibility to get this compiled would probably be to follow the message in the `PyComTest.dsp` file which says:

> !MESSAGE  This is not a valid makefile. To build this project using NMAKE,
!MESSAGE use the Export Makefile command and run
!MESSAGE
!MESSAGE NMAKE /f "PyCOMTest.mak".

However, this would require a version of Visual Studio that can still read the project to export which I don't have.

Please let me know if PyComTest is the way to go.

**Comment by geppi** [comment]
> I was hoping to receive some feedback about what would be required to merge this PR and have in the meantime taken a look into the testing facility of this project. I discovered the sources for the C++ PyComTest server-dll and the related Python unittest files which seem to me the most appropriate place to implement a test case for this PR.
> 
> However, I've also noticed that in CI these tests are not used and that the PyCOMTest sources only contain rather old versions of Visual Studio 6.0 project files. Therefore I'm wondering if the PyComTest server-dll is still actively used locally by the maintainers of this project and if there are probably project files available for some recent version of Visual Studio?
> 
> Another possibility to get this compiled would probably be to follow the message in the `PyComTest.dsp` file which says:
> 
> > !MESSAGE  This is not a valid makefile. To build this project using NMAKE,
> > !MESSAGE use the Export Makefile command and run
> > !MESSAGE
> > !MESSAGE NMAKE /f "PyCOMTest.mak".
> 
> However, this would require a version of Visual Studio that can still read the project to export which I don't have.
> 
> Please let me know if PyComTest is the way to go.

**Comment by mhammond** [comment]
pycomtest is certainly the right vehicle for testing. I'm afraid I'm a bit swamped at the moment, so it might be a little time before I can give meaningful feedback here.

**Comment by geppi** [comment]
I managed to compile the C++ PyComTest server-dll with Visual Studio 2022 and added the method `ModifyStruct` to the `IPyCOMTest` interface to implement a unittest for this PR.
Normally a COM interface should not be modified as soon as it is published. However, since this is a test interface purely internal to this project, it is not really published and I do not see a problem in extending the existing interface. If absolutely desired the new method could of course be moved into a new interface but this would also require an additional component to implement the method.

The test case has been added to `testPyComTest.py` and is limited to the non _Dynamic_, i.e. _Generated_ case.

**Comment by geppi** [comment]
Is there any chance that this gets merged?

Please let me know what is missing.

**Review by mhammond — APPROVED** [review]
Sorry for the delay, this looks great, thanks!

**Comment by Avasam** [comment]
Is this worth adding an entry in `CHANGES.txt` ?

**Pull request merged**
