### PR TITLE
Optional creation of a text-only package

### PR DESCRIPTION
**Pull request by markuskramerIgitt**
## Intention
Allow the optional creation of a text-only pywin32 package.

A text-only package is beneficial for projects using only the textual components of pywin32 (no sound, no graphics). 

Benefits are:
- Reduce vulnerability: the MFC library is large and (earlier? versions) contained CVE's. 
- Reduce maintenance cost: by shipping less, you need to observe less, and patch less.
- Reduce resources: less size mean less disk space and less network bandwidth.

The resulting text-only wheel is 1/3 of the size of the full package: 

| Package                                          | Size 
|---                                               |---
| `pywin32textonly-227.1-cp37-cp37m-win_amd64.whl` | 2.6 MB
| `pywin32-227.1-cp37-cp37m-win_amd64.whl`         |  6.8 MB

## Description
I tried to remove all packages and extensions related to GUI in setup.py

I initially thought I could use the distutil `options` parameter, but could not find documentation, so I used a Windows environment variable. How can I use the distutil `options` parameter ([setup.py](https://github.com/mhammond/pywin32/blob/5f47dc1167270148880110f5b6541eb9e998c4d0/setup.py#L2496) line 2496)?

I tried to change the minimal number of lines. 

## Usage 

    set pywin32_text_only=True
    python setup.py bdist_wheel 

    set "pywin32_text_only="
    python setup.py bdist_wheel

### CODE REVIEW

**Comment by markuskramerIgitt** [comment]
What can I do about the first (3.8, x86) CI test failure ?
```
Expected:
    datetime.timedelta(-1, 61200)
Got:
    datetime.timedelta(days=-1, seconds=61200)
```

**Comment by mhammond** [comment]
Sorry, but I've no interest in this. Specifically, it will *increase* my maintenance and resource costs.

**Comment by vernondcole** [comment]
Ouch!  That's a bit harsh.
As a fellow SaltStack user, I am also interested in this. Salt installs a
private copy of Python, as a Python virtual environment. The GUI stuff is
bloat, in that location.
On a usual workstation, I would have two copies of pywin32. The one
installed on the default Python, and the one in
C:\salt\bin\libs\site-packages.
(Actually, I personally have many more copies, one for each Python version
that I test, but that is not a usual case.)
If I am using pywin32 in a service (like, let's say, dropbox or torrent) I
can really benefit from the reduced download size.
Can we reconsider this? A code fork would be a bad idea.

**Comment by mhammond** [comment]
> Salt installs a private copy of Python, as a Python virtual environment. The GUI stuff is bloat, in that location.

There's lots of python that's bloat in that context though, right? I'll reconsider it it's a common pattern used by Python packages or Python itself.

**Pull request closed without merging**
