### PR TITLE
Clang format all c++ sources

### PR DESCRIPTION
**Pull request by konserw**
This has been done with clang-format and format file from https://github.com/closeio/ciso8601/blob/master/.clang-format that should approximate PEP 7 style.
This supersedes #1318

### CODE REVIEW

**Comment by konserw** [comment]
@mhammond, @thopiekar could you please review?

**Comment by konserw** [comment]
I can see 2 points to discuss:
1) 80-char line width - don't you think it's really too narrow? Maybe 120 would be more reasonable?
2) I really don't like line break between return type and function name, and haven't seen such formatting here before - should I revert that part?

**Comment by mhammond** [comment]
Thanks! I agree we should widen the default to 120 - I've also hated an 80 char limit! And yeah, that extra linebreak rule seems dumb too.

Should we introduce this gradually? eg, land basic clag formatting with, say, just tab/space fixups, then introduce other fixes as separate PRs? Or just the less controversial rules?

I haven't looked in detail tho - I'll try and do so this weekend.

**Comment by thopiekar** [comment]
@mhammond: great, thank you for taking time!

Yes, I find some conventions in pep8 also stupid. They are too strict in my point of view.
I think it would be good to have a statement somewhere (Contribute.md?) which says: "Pythoncode needs to comply to PEP8 except: Blabla..". Same for PEP7, but I haven't found a codestyle checker for it. Only a tool in the Clang toolchain, which does autoformatting automatically. Could maybe ask git whether differences are made to the code and then complain in our CI about it 🤔

**Comment by v-python** [comment]
120 column cards don't fit in my card punch.

**Comment by konserw** [comment]
Yes you can use clang with git to check formatting in ci, check for example
cucumber-cpp

pt., 26 lip 2019, 20:08 użytkownik v-python <notifications@github.com>
napisał:

**Comment by thopiekar** [comment]
Thank you for the hint. I found it in their travis.sh:
https://github.com/cucumber/cucumber-cpp/blob/master/travis.sh#L33

**Comment by mhammond** [comment]
I don't think we need to get too excited or over-engineer things here. If the toolchain configs are checked in then we just need to say something like "please comply with those toolchains", right? :)

**Comment by konserw** [comment]
> * 80-char line width - don't you think it's really too narrow? Maybe 120 would be more reasonable?
> 
> * I really don't like line break between return type and function name, and haven't seen such formatting here before - should I revert that part?

I've changed line width to 120 chars and disabled line break after return type. Any other comments on style?

> Should we introduce this gradually? eg, land basic clag formatting with, say, just tab/space fixups, then introduce other fixes as separate PRs? Or just the less controversial rules?

To be honest it's easier to run clang-format with final configuration on everything at once. 
Also  after changing above 2 rules we have now 50k lines of changes less then before :) But of course if you think it would be beneficial to split this change into few steps I can try preparing such PRs.

BTW. I've also rebased on top of current master.

**Comment by konserw** [comment]
Rebased on top of current master due to conflicts that arose this morning.
Please let me know if I'm rebasing for nothing ;)

**Comment by thopiekar** [comment]
@mhammond How about merging this before someone touches one of the C++ files?
As far as I understood auto formatting has been done and the code compiles.

**Comment by mhammond** [comment]
Sorry for the delay here - I pushed a tweaked version that doesn't touch some "external" sources, such as scintilla and some MAPI files. At a later date, I can work out how to configure clang-format to exclude those directories :)

Thanks heaps!

**Comment by mhammond** [comment]
I should mention: merged in 059b7beb

**Pull request closed without merging**
