### PR TITLE
Fix loader path

### PR DESCRIPTION
**Pull request by xoviat**
Closes gh-1151.

### CODE REVIEW

**Comment by xoviat** [comment]
@mhammond Could you please merge this?

**Comment by mhammond** [comment]
> @mhammond Could you please merge this?

I'll certainly do something like this before the next build - I'm yet to check if a comment works OK in a .pth file (to say exactly why the line exists), and it seems fairly easy to add a different/alternative .pth file only for wheels (to mitigate a small risk the PATH change has a side-effect we haven't considered when the .dll files have also had the post-install treatment).

I'm not likely to make a new build in the next few weeks - is there urgency here? Given the recent pypiwin32 changes, is there anyone actually broken by this at the moment?

**Comment by Erotemic** [comment]
> is there anyone actually broken by this at the moment?

I'm currently working around it. So, my packages aren't broken per-say, but it would be nice to remove the workaround.

**Comment by mhammond** [comment]
(FTR, I did try using a separate .pth file used only by pip, but that started to get too convoluted, so I just added it to the existing .pth file with comments.)

**Pull request closed without merging**
