### PR TITLE
Remove PRIVATE symbols from /EXPORTs

### PR DESCRIPTION
**Pull request by stevenwinfield**
Potential fix for the LNK1161 error described in https://github.com/mhammond/pywin32/issues/1375

### CODE REVIEW

**Comment by mhammond** [comment]
This seems like a safe change, thanks!

**Comment by thopiekar** [comment]
Hello @stevenwinfield and @mhammond,

I have concerns about this PR. It seems like something gets stuck when running the test suite. The CI doesn't tell me where, but I assume it is win32com.
With this PR python2.7 builds are stuck:
* https://ci.appveyor.com/project/thopiekar/pywin32/builds/27086765
and after reverting them they pass again:
* https://ci.appveyor.com/project/thopiekar/pywin32/builds/27091205

Maybe you can discuss how it comes and/or find an alternative solution?
To be honest, it is out of my scope to understand what is going on. 😬

**Comment by stevenwinfield** [comment]
@theopiekar 
I put a somewhat detailed explanation with this commit: https://github.com/mhammond/pywin32/commit/117af005f92fd66f05e0556e1f8528559d903c38

The issue should be reproducible by trying to build with the latest version of the 2017 or 2019 MSVC build tools (i.e. not a full Visual Studio install, though that might reproduce it too)

**Comment by thopiekar** [comment]
Understand. But without your change we have no errors in newer VisualStudio versions, too, and all tests run without getting stuck.
Anyway, I believe that you did it correctly, but that made something (a bug?) active that makes the test suite stuck with Python 2.7.

**Comment by stevenwinfield** [comment]
@thopiekar It actually looks like *all* tests are actually failing, but the CI is marking them as passed 😢 

E.g. [This run](https://ci.appveyor.com/project/thopiekar/pywin32/builds/27086765/job/xko88uim8a4died9?fullLog=true) is marked as a success, but from around line 4000 you can see lots of test errors. I'm assuming this isn't expected?

So (now that I'm back at a physical keyboard!) here's a fuller explanation of what I was trying to do:

In `setup.py`, the `WinExt` class is derived from `distutils.core.Extension`, which has an `export_symbols` argument - which is supposed to be a list of symbols that the extension should export. When using MSVC, each entry in this list is used directly in a `/EXPORT:...` specification when linking.

However, `/EXPORT` specifications can contain more than just the symbol name - as shown [here](https://github.com/mhammond/pywin32/pull/1394/commits/117af005f92fd66f05e0556e1f8528559d903c38) they can contain ordinals and directives, separated by commas.

Knowing this, `WinExt.__init__` calls `Extension.__init__` with a list of such comma-separated-symbols-and-directives, which it gets from `parse_def_file()`, in order to get the actual `/EXPORT` specifications emitted that it wants.

As noted, though, the most recent MSVC linkers are no longer silently swallowing the `PRIVATE` directive, which the docs say can only appear in a `.def` file.

Clearly, omitting the `/EXPORT` spec for these `PRIVATE` symbols is causing problems, for reasons that I'm unfamiliar with.

Two suggestions:
- Reproduce the issue on AppVeyor by using an environment with the lastest update to the 2017 or 2019 compilers (e.g. 14.16.*)
- Perhaps instead of using `export_symbols`, pass a `/DEF:filename.def` spec to `WinExt` in `extra_link_args` - I assumed there was a good reason for not doing this in the first place, but I could be wrong

**Comment by mhammond** [comment]
There's no .def file as I simply didn't want to maintain one :) If there's no simple solution here, we should revert the change until one is found.

**Comment by stevenwinfield** [comment]
@mhammond what about the .def files that `parse_def_file()` is parsing?

**Comment by mhammond** [comment]
It looks like this is exactly 2 .def files. If you can pass them directly to the linker instead of parsing them, then that would be great (and yeah, I suspect there was *some* reason we didn't just do that in the first place, but I've no idea what that might be!)

**Pull request merged**
