### PR TITLE
CI: Adding AppVeyor CI (v2)

### PR DESCRIPTION
**Pull request by thopiekar**
Second version, which includes all work I did before.
It needs fixes and tweaks to some files, like setup.py.
Additionally, it does no real tests at the moment and also does not use the latest SWIG to build the C extensions.

However, at least something that is usable.

### CODE REVIEW

**Comment by thopiekar** [comment]
#1200 needs to be fixed.

**Comment by mhammond** [comment]
Great, thanks - I'll merge this and we can see what the fallout is :)

**Comment by thopiekar** [comment]
No problem. The only thing, which won't work ever, are Python 2.7 builds. The main reason is that AppVeyor comes with Visual Studio 2008 Express, but only the Standard and Professional edition are providing the needed directory with the MFC90 libraries.

I sent yesterday a mail to the AppVeyor team to ask whether it is possible to upgrade it or not.

There is an alternative in my mind, which could be to offer a download to the redist installer, but never tested, whether PyWin32 will work with it.

**Comment by bdbaddog** [comment]
Would this package work?

https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by mhammond** [comment]
I'd be fine with having AppVeyor just perform a build and not bother trying to create the installation artifacts. I'd also be fine with a simple change to setup.py so it looks in another location, but I'd be less keen on having it download and install the redist package as part of the build process.

**Comment by thopiekar** [comment]
Alright. There is good news from my side. I contacted the Appveyor people again and they said that you can take the redistributable libraries from the {WINDOWS_INSTALL}/Windows/WinSxS directory. I will try to find a way how to get them from there.

**Pull request merged**
