### PR TITLE
Fix import error when using a custom cache location

### PR DESCRIPTION
**Pull request by jmoraleda**
### Background ###

One of the work arounds when users don't have admin privileges is to create a custom cache location as described in https://github.com/mhammond/pywin32/issues/1143#issuecomment-746261942

### Problem ###

Unfortunately that work around does not work when trying to import a module that has not already been generated:

```
  File "C:\Users\jorge\test\msword.py", line 90, in __init__
    self.comWordApp = win32.DispatchWithEvents('Word.Application', _COMWordApp)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WPy64-31120b3\python-3.11.2.amd64\Lib\site-packages\win32com\client\__init__.py", line 323, in DispatchWithEvents
    gencache.EnsureModule(tla[0], tla[1], tla[3], tla[4], bValidateFile=0)
  File "C:\Program Files\WPy64-31120b3\python-3.11.2.amd64\Lib\site-packages\win32com\client\gencache.py", line 601, in EnsureModule
    module = MakeModuleForTypelib(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WPy64-31120b3\python-3.11.2.amd64\Lib\site-packages\win32com\client\gencache.py", line 318, in MakeModuleForTypelib
    makepy.GenerateFromTypeLibSpec(
  File "C:\Program Files\WPy64-31120b3\python-3.11.2.amd64\Lib\site-packages\win32com\client\makepy.py", line 338, in GenerateFromTypeLibSpec
    gencache.AddModuleToCache(info.clsid, info.lcid, info.major, info.minor)
  File "C:\Program Files\WPy64-31120b3\python-3.11.2.amd64\Lib\site-packages\win32com\client\gencache.py", line 647, in AddModuleToCache
    mod = _GetModule(fname)
          ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WPy64-31120b3\python-3.11.2.amd64\Lib\site-packages\win32com\client\gencache.py", line 726, in _GetModule
    mod = __import__(mod_name)
          ^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'win32com.gen_py.00020905-0000-0000-C000-000000000046x0x8x5'
```

### Solution ###

This PR fixes the above bug by attempting to import the module from the custom location if the import from the default location fails.

### CODE REVIEW

**Comment by mhammond** [comment]
I don't quite understand the problem. Is win32com.__gen_path__ not the same as win32com.gen_py.__path__[0]? At face value, it looks like you are failing to load the module from some directory, so falling back to a different way of loading the module from the exact same directory?

**Comment by jmoraleda** [comment]
Thank you for your quick reply and for your work in this library!

The issue has to do with an inconsistency between where a module is generated when it is not present (that directory is   `win32com.__gen_path__`) and  the list of directories that is searched in `__import__` statements (that list is `sys.path`).

In particular:

*  When a module is not present, it is generated in `win32com.__gen_path__`. This is as it should be.
* But the statement 
```
    mod_name = "win32com.gen_py.%s" % fname
    mod = __import__(mod_name)
```
fails because the module that was just generated is not in a subdirectory `\win32com\get_py` of any directory in `sys.path`

The fix detects when an import fails and then
1. adds `win32com.__gen_path__` temporarily to syspath and
2. attempts to import the module directly from there (where it actually is) and not from subdirectory `win32com\get_py`

**Comment by mhammond** [comment]
I'd expect `win32com.__gen_path__` and `win32com.gen_py.__path__[0]` to point at the same place though - IOW:

this means:

>  When a module is not present, it is generated in win32com.__gen_path__. This is as it should be.

Right - so any files, or directories with __init__.py created here should be importable using:

>   mod_name = "win32com.gen_py.%s" % fname

ie, what's different about your environment that makes this work for everyone else? It's not the permissions problem you quoted, because according to the description above, you are able to write to the directory in question.

**Comment by jmoraleda** [comment]
> I'd expect win32com.__gen_path__ and win32com.gen_py.__path__[0] to point at the same place though

Why do you expect that?

To set a custom path I am doing
```
# Ensure win32com cache uses a location writable by the user
com32_cache.mkdir(exist_ok=True)
win32com.__gen_path__ = str(com32_cache)
```
`com32_cache` is is a `pathlib.Path` variable pointing to the user writable directory that I want to use for cache and is unrelated to the installation directory of pywin32 and thus `win32com.gen_py`. Am I doing something wrong?

**Comment by jmoraleda** [comment]
Thank you again. What is the way the library expects for the end user to set `win32com.__gen_path__ ` given that they can't modify win32com code?

The issue in detail:

In our set up pywin32 is installed in the user computers (via `pip`) by an administrator as part of a larger bundle of code, but it is intended to be used by users without elevated privileges. Regular users are not allowed to install software via `pip`.

I attempted to make win32com work in this setting for regular users with the code:
```
import win32com
com32_cache.mkdir(exist_ok=True)
win32com.__gen_path__ = str(com32_cache)
```

But this code resets `__gen_path__` _after the import which in particular means the code  https://github.com/mhammond/pywin32/blob/main/com/win32com/__init__.py#L121-L129 has already run, so it is not going to reset `win32com.gen_py.path[0]` equal to `win32com.__gen_path__`  which is why I am suggesting this PR.

But if this is not the right solution, what is the way the library expects for the end user to set `win32com.__gen_path__ ` given that they can't modify win32com code?

**Comment by mhammond** [comment]
The intention is that there should not exist a `win32com/gen_py` directory, so [this code](https://github.com/mhammond/pywin32/blob/main/com/win32com/__init__.py#L113) will try and use directory under %TEMP%.

**Comment by jmoraleda** [comment]
Thank you again for your help!

I just tried a fresh installation of pywin32 via pip as an admin and I can confirm that it indeed behaves as you say and sets gen path to ` C:\Users\jorge\AppData\Local\Temp\gen_py\3.11`.

So the problem is indeed specific to our environment. I am closing this pull request since it is clear to me now that this is not the right way to proceed. Thank you again.

In case others encounter the same problem: In our setup our admins do not run pip on the end user machines, instead they run pip in a build machine and then build an approved windows installer that installs python as well as authorized packages (including pywin32) by directly writing files to the end user machines. The installer also runs `pywin32_postinstall.py` (also with elevated privileges). I need to look more in detail but somewhere we are incorrectly creating a `win32com/gen_py` directory which is the source of the problem.

**Pull request closed without merging**
