### PR TITLE
Corrected wMilliseconds truncation in PyTime::getattro().

### PR DESCRIPTION
**Pull request by dbivolaru**
This should fix Issue #387

### CODE REVIEW

**Comment by dbivolaru** [comment]
@mhammond Mark, I updated as requested.

**Comment by dbivolaru** [comment]
@mhammond Hi Mark, this should be resolved now. Can you have a look? Best Regards, Dorian

**Comment by dbivolaru** [comment]
@mhammond Hi Mark! Let me know if you have any other concersn.

**Comment by mhammond** [comment]
Sorry for the delay, but thanks, this looks great!

**Pull request merged**
