### PR TITLE
Optimized Images by the GitHub [ImgBot] (49.58kb -> 47.87kb (3.45%))

### PR DESCRIPTION
**Pull request by AYIDouble**
[ImgBot] optimizes images

*Total -- 49.58kb -> 47.87kb (3.45%)

/com/win32comext/axscript/demos/client/ie/pycom_blowing.gif -- 20.44kb -> 19.61kb (4.05%)
/com/win32com/HTML/image/pycom_blowing.gif -- 20.44kb -> 19.61kb (4.05%)
/com/win32com/HTML/image/pythoncom.gif -- 5.63kb -> 5.59kb (0.76%)
/Pythonwin/doc/debugger/pythonwin.gif -- 1.40kb -> 1.40kb (0.42%)
/Pythonwin/doc/pythonwin.gif -- 1.40kb -> 1.40kb (0.42%)
/com/win32com/HTML/image/www_icon.gif -- 0.27kb -> 0.27kb (0.36%)

### CODE REVIEW

**Comment by AYIDouble** [comment]
It's a official tool from the GitHub Marketplace: https://github.com/marketplace/imgbot

> ImgBot will crawl through all of your image files in GitHub and losslessly compress them. This will make the file size go down, but leave the dimensions and quality untouched.

**Comment by mhammond** [comment]
I'm having trouble getting excited by a saving of less than 2kb!

**Comment by AYIDouble** [comment]
Only the file size changes, everything else stays the same.
It was just something that caught my eye.

**Comment by mhammond** [comment]
Thanks for this, but I don't think it's valuable enough to land.

**Pull request closed without merging**
