### PR TITLE
Added CI job to check black formatting

### PR DESCRIPTION
**Pull request by LincolnPuzey**
I have tested this in a PR in my fork, seems to work well.

Haven't actually formatted the repo with black yet, that can be done after merging this.
@mhammond I figured I'll let you take the git-blame credit for that.

I also started off the `.git-blame-ignore-revs` file with a commit I think makes sense to ignore.

### CODE REVIEW

**Comment by LincolnPuzey** [comment]
Currently all `.py` and `.pyi` files in the repo are checked by black. Are there any that should be excluded from the check?

**Comment by LincolnPuzey** [comment]
Update: have removed config file so black runs with 100% default settings

**Comment by mhammond** [comment]
Thanks for this - I'll get to it soon.

**Comment by LincolnPuzey** [comment]
I can add back the config file if you want a custom line length (current default is 88) or another non-default setting.

I could also set the existing `test` job to require the new `black` one - so the unit tests won't run unless the code is formatted correctly.

**Pull request merged**
