### PR TITLE
Fix python 2.7 build on x86-64 by adding some headers

### PR DESCRIPTION
**Pull request by konserw**
Fix python 2.7 build on x86-64
Based on https://around-the-corner.typepad.com/adn/2014/10/building-pywin32-for-motionbuilder-2015.html
What I've done is:
1. Added necessary headers to new 3rd_party directory within pywin32 repository
2. Added step in appveyor.yml to copy over those headers into `C:\Program Files (x86)\Windows Kits\8.1\Include\um` only in case of python 2.7 for x86-64

### CODE REVIEW

**Comment by konserw** [comment]
Fixes or workarounds issue #1277

**Comment by mhammond** [comment]
Thanks for this, but I'm not sure what the license issues are for putting these headers in the repo. Given this is just for automation, I'd probably prefer to arrange for these modules to be skipped - setup.py already has very basic support for "skipping" the build of certain modules.

**Comment by konserw** [comment]
As for license, most of those headers are from here: https://github.com/stephenegriffin/mfcmapi it's MIT licensed. Unfortunately  files are from MS download: https://www.microsoft.com/en-us/download/details.aspx?id=12905 without any info on their license. 
I'm not insisting on pushing this though. Skipping sounds also right, I just don't know how to do it ;)

**Comment by mhammond** [comment]
Fixed by #1313

**Pull request closed without merging**
