### PR TITLE
[WIP] CI: Run all tests

### PR DESCRIPTION
**Pull request by thopiekar**
Known issues:
- Some scripts seem to hang. At least it does on locally my computer.

### CODE REVIEW

**Comment by mhammond** [comment]
This is awesome! The pywintypes load failure is a shame - all of that stuff is way too complicated, so feel free to be aggressive with that load script if it would help.

**Comment by thopiekar** [comment]
No problem. Just noticed that the test script is delivered with the distributed files, but never run in the CI. Logically that is too late, because the tests must success after the files are delievered to the end-user.
Yes, I'm already experimenting with PYTHONUSERBASE in a different branch. Setting PYTHONPATH won't execute the pywin32.pth file.
The current status is that I'm doing an installation via --user, but that gives an error because something that this os.join'd is None.
Will keep you posted 😉

**Comment by thopiekar** [comment]
Tests pass, if I disable win32 tests. Probably because user inputs are needed.
https://ci.appveyor.com/project/thopiekar/pywin32/builds/26944078

**Comment by thopiekar** [comment]
Closing this as #1400 follows up on this..

**Pull request closed without merging**
