### PR TITLE
Use new unicode API in win32sysloader

### LINKED ISSUE #1802: pywintypes.py: DeprecationWarning: getargs: The 'u' format is deprecated. Use 'U' instead.
* Expected behavior and actual behavior.

No `DeprecationWarning` should be shown.

* Steps to reproduce the problem.

```py
> cat test_pywin32.py
def test_pywin32():
    import pywintypes

> pytest .\test_pywin32.py
===================================================== test session starts =====================================================
platform win32 -- Python 3.10.0, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: D:\cli\testproj
plugins: forked-1.3.0, xdist-2.4.0
collected 1 item

test_pywin32.py .                                                                                                        [100%]

====================================================== warnings summary =======================================================
test_pywin32.py::test_pywin32
  D:\cli\py310\lib\site-packages\win32\lib\pywintypes.py:54: DeprecationWarning: getargs: The 'u' format is deprecated. Use 'U' instead.
    found = _win32sysloader.GetModuleFilename(filename)

test_pywin32.py::test_pywin32
  D:\cli\py310\lib\site-packages\win32\lib\pywintypes.py:68: DeprecationWarning: getargs: The 'u' format is deprecated. Use 'U' instead.
    found = _win32sysloader.LoadModule(filename)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================ 1 passed, 2 warnings in 0.13s ================================================
```

* Version of Python and pywin32

```
> python -V
Python 3.10.0

> pip list | Select-String pywin32

pywin32                                 302
```

### PR DESCRIPTION
**Pull request by Tolker-KU**
Closes #1802

### CODE REVIEW

**Comment by Tolker-KU** [comment]
I've pinned the version of setuptools at 59.6.0 in CI. This is probably not something we want, but new versions make CI fail. Havn't done much digging on what causes the failure but it seems that it has something to do with the bundled distutils and bdist_wininst

**Review by mhammond — CHANGES_REQUESTED** [review]
This looks great, thanks. I'll look at the pip install later, but in the meantime, do you mind removing the `#ifdef UNICODE` blocks, removing the `else` parts - the code will no longer ever be built with UNICODE not being defined.

**Review by mhammond — APPROVED** [review]
Thanks!

**Comment by Tolker-KU** [comment]
Happy to help!

**Pull request merged**
