### PR TITLE
Py 3.10 merge test

### PR DESCRIPTION
**Pull request by mhammond**
This is a slight rework of #1664 - I cherry-picked many of the commits, but took a slightly different approach in the others. I'm doing this as a PR just to ensure I didn't break anything in CI.

@kxrob thanks heaps for your work here - I think I got everything from that PR, but feel free to call me out if I missed something.

### CODE REVIEW

**Comment by kxrob** [comment]
@mhammond "Test tweaks" : the tests now run all green in 8 seconds. The main tests seem not to be really executed (or errors catched).

**Comment by LincolnPuzey** [comment]
@mhammond You should update the python version classifiers in `setup.py`

**Comment by mhammond** [comment]
> @mhammond "Test tweaks" : the tests now run all green in 8 seconds

I'm seeing them take 8 *minutes* - eg: https://github.com/mhammond/pywin32/runs/3454090504?check_suite_focus=true

```
 test (3.10-dev, x64)
succeeded 16 hours ago in 7m 57s 
...

They are ignoring failures, but that seems as though it has been true forever (eg, [this run](https://github.com/mhammond/pywin32/runs/2988279866?check_suite_focus=true) from July shows green, but looking at the output I'm seeing roughly the same COM failures I see in #1752 - although that is reporting failure as failure).

So it's not clear that I've regressed much here? Regardless, it will likely be a while before I poke much more at this, but welcome any other insights

**Comment by kxrob** [comment]
> I'm seeing them take 8 _minutes_

The 7 .. 8 min are the total CI check runtime, the tests only are 7s or 8s since.
The last master commit with checks before "Test tweaks" is https://github.com/mhammond/pywin32/runs/3357259770 and had 1+ minute runtime for the tests specifically, and accordingly more for the total runtime.
Majority came from "_Ran 244 tests in 52.097s_". Those seem to be missing now in the output, and it immediately goes to
"_Executing level 2 tests - 95 test cases will be run_" since then.

**Comment by mhammond** [comment]
> The 7 .. 8 min are the total CI check runtime, the tests only are 7s or 8s since.

Oh yes, I see. I'm still trying to work out what's going on. win32com tests were ignored which doesn't help :) There's strangeness in the COM failures in CI, which I can't reproduce locally. I think adding "-v" to the CI tests can't hurt.

**Pull request merged**
