### PR TITLE
Replace imp module with importlib #1256

### PR DESCRIPTION
**Pull request by efahl**

### CODE REVIEW

**Comment by mhammond** [comment]
Thanks!

**Comment by efahl** [comment]
Mark, thanks to you for pywin32, been using it for many years.

I have been waiting for Python 2 support to be dropped before submitting this.  I think it covers both #1256 and #1503, so you should be able to close those.

**Comment by brgirgis** [comment]
When is this change scheduled to be released?

**Comment by henrycjc** [comment]
Hello @mhammond - could you please create a new release of pywin32 to include the changes in this PR? Per https://github.com/mhammond/pywin32/issues/1256

**Pull request merged**
