### PR TITLE
convert spaces to tabs in win32pdhmodule

### PR DESCRIPTION
**Pull request by konserw**

### CODE REVIEW

**Comment by thopiekar** [comment]
By the way, could we add somewhere a document about coding conventions?
Personally, I believed that PyWin32 prefers 4-whitespaces, since many projects are using them already :sweat_smile:

**Comment by konserw** [comment]
@thopiekar even better would by clang format file, and step in CI that would check for violations ;) 
As for tabs - I just did what generated smaller diff for that file

**Comment by thopiekar** [comment]
No question! 😋

**Comment by mhammond** [comment]
Sorry for the delay here.

I agree that documenting conventions should be done - lots of the c++ files in particular use a mix of tabs and spaces, which is bad by any measure! However, I think it makes sense to stick with pep-7, in the same way that @thopiekar is trying to ensure all .py code is pep-8 compliant. This PR has conflicts, so will need to be updated in some form, so if you move it to what pep-7 dictates I'll take the PR. clang-format is probably a better option still, but we don't need to boil the ocean.

**Comment by konserw** [comment]
Quick google search allowed me to find clang format file imitating pep-7 (I didn't know there is pep-7 tbh! :) heard only of pep-8): https://github.com/closeio/ciso8601/blob/master/.clang-format  shall I try applying it to all C source files here?

**Comment by thopiekar** [comment]
Yes, that would be great. Pull all changed from master and apply the
formatting on all C/C++ files. I have the feeling that most contributions
via PRs are targeting Python or SWIG files. Therefore a good timing to
cleanup all C/C++ files.

How do you think @mhammond? 😉

>

**Comment by mhammond** [comment]
Yeah, SGTM, thanks.

**Comment by konserw** [comment]
I've just created new PR #1374 for this.

**Pull request closed without merging**
