### PR TITLE
Consistent usage of end-of-statement marker with macros (better clang-format out of the box) & Make the CI step actually fail on failure

### LINKED ISSUE #1412: clang-format issue with macro
By chance, I noticed the following happened, and I'm mentioning it in case it's early enough/worth the effort to fix.

One example:
https://github.com/mhammond/pywin32/blob/059b7beb928225e389621802db758c75a7b8c58f/win32/src/win32apimodule.cpp#L133-L136

### PR DESCRIPTION
**Pull request by Avasam**
Closes #1412
Found with the regex `#define .+?;` (it may not find everything, but found a few)
Alternatively, the `;` can be removed from the macros themselves to force adding it in-code, not having to add any configuration (my instinct is to say that might be clearer for devs anyway, and removes specialized configuration, but up to you)

(I'll add an entry to the `.git-blame-ignore-revs` after its decided which solution you prefer)

### CODE REVIEW

**Review by mhammond — APPROVED** [review]
Thanks!

**Comment by Avasam** [comment]
@mhammond Just to confirm before I add to the .git-blame-ignire: you prefer this config change over removing `;` from the macro so that is has to be added when used in code?

**Comment by mhammond** [comment]
> @mhammond Just to confirm before I add to the .git-blame-ignore: you prefer this config change over removing `;` from the macro so that is has to be added when used in code?

I don't have a strong opinion here, but I think it kinda seems more natural for people to not use a trailing `;` with macros. OTOH, with our checkers in place, maybe it is fine to start insisting on the `;`.

WDYT?

**Comment by Avasam** [comment]
My gut feeling is that it would be nice not special case certain methods in configuration. It would also make usage more consistent (for example `PYWIN_MODULE_INIT_RETURN_ERROR` usage is followed by `;` in 87/90 cases).

**Comment by Avasam** [comment]
> It would also make usage more consistent (for example `PYWIN_MODULE_INIT_RETURN_ERROR` usage is followed by `;` in 87/90 cases).

@mhammond This commit of this PR shows the difference: [`a0cab65` (#2405)](https://github.com/mhammond/pywin32/pull/2405/commits/a0cab65b1248a153d271fc40a1ce9f478e7b43bc)

**Review by mhammond — APPROVED** [review]
Thanks!

**Pull request merged**
