### PR TITLE
setup.py: Adding lookup for Visual Studio 2017

### PR DESCRIPTION
**Pull request by thopiekar**

### CODE REVIEW

**Comment by thopiekar** [comment]
Tested it here locally and seems to work fine, even if the AppVeyor builds are not underlining it:
```
ab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexProgress.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexPS.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexPython.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexR.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexRebol.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexRuby.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexScriptol.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexSmalltalk.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexSpecman.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexSpice.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexSQL.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexTADS3.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexTCL.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexTeX.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexVB.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexVerilog.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexVHDL.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\LexYAML.obj C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\ScintRes.res KERNEL32.lib USER32.lib GDI32.lib IMM32.lib OLE32.LIB
ScintillaWinL.obj : warning LNK4197: export 'Scintilla_DirectFunction' specified multiple times; using first specification
   Creating library C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\Scintilla.lib and object C:\Users\THOMAS~1\GitLab\pywin32\build\TEMPWI~1.6\Release\SCINTI~1\Scintilla.exp
copying build\temp.win-amd64-3.6\Release\scintilla\scintilla.dll -> build\lib.win-amd64-3.6\pythonwin
creating build\lib.win-amd64-3.6\win32\libs
copying build\temp.win-amd64-3.6\Release\pywintypes.lib -> build\lib.win-amd64-3.6\win32\libs
creating build\lib.win-amd64-3.6\win32com\libs
copying build\temp.win-amd64-3.6\Release\pythoncom.lib -> build\lib.win-amd64-3.6\win32com\libs
copying build\temp.win-amd64-3.6\Release\axscript.lib -> build\lib.win-amd64-3.6\win32com\libs
running build_scripts
creating build\scripts-3.6
copying pywin32_postinstall.py -> build\scripts-3.6
Refactoring build\scripts-3.6\pywin32_postinstall.py
copying pywin32_testall.py -> build\scripts-3.6
Refactoring build\scripts-3.6\pywin32_testall.py
*** NOTE: The following extensions were NOT built:
 exchange: No 64-bit library for utility functions available.
 exchdapi: No 64-bit library for utility functions available.
For more details on installing the correct libraries and headers,
please execute this script with no arguments (or see the docstring)
```

**Comment by mhammond** [comment]
I'm not particularly interested in building from within vs2017 - is that what the .project files are for? I'm also not sure why vs2017 is of interest yet - isn't python 2.7 still built with 2015?

**Comment by thopiekar** [comment]
Ah, good that you mentioned it. No, these are files created by eclipse (+pydev plugin), which I use for development.
Well, I'm not focusing and not testing Python 2.7 at all anymore. All I can say is that building against VS2017 and using the built binaries on Python3.5 works perfectly fine.
Building with it worked before already, but since you added the "MS SDK not found" check it does not build anymore. I have no idea why this lookup is needed because it seemed to work without any lookup before or (!) something changed on my system since then.

**Comment by thopiekar** [comment]
Continued at: #1188

**Pull request closed without merging**
