### PR TITLE
Black

### PR DESCRIPTION
**Pull request by mhammond**
Hey @LincolnPuzey, thanks for #1747 - do you mind having a quick sanity-scan of this?

### CODE REVIEW

**Comment by mhammond** [comment]
huh - apparently I'm using `version 21.8b0` - I assume the github action is using something different. Any advice for ensuring I always use the same version as CI?

**Comment by LincolnPuzey** [comment]
Weird I though the action should be using `21.8b0` as well since the [docs](https://black.readthedocs.io/en/stable/integrations/github_actions.html) say

>The version of Black the action will use can be configured via version. The action defaults to the latest release available on PyPI. Only versions available from PyPI are supported, so no commit SHAs or branch names.

and that is the latest.

**Comment by LincolnPuzey** [comment]
When I checkout your branch and run black it complains about the same files as the action, with the same diff if I run with `--diff`,

```
(.venv) C:\Users\Lincoln\Projects\pywin32>black --version
black, version 21.8b0

(.venv) C:\Users\Lincoln\Projects\pywin32>black --check .
would reformat win32\Lib\win32evtlogutil.py
would reformat com\win32com\makegw\makegwparse.py
would reformat adodbapi\adodbapi.py
Oh no! � � �
3 files would be reformatted, 463 files would be left unchanged.
```

So the action seems right? For some reason you got a different formatted output.

**Comment by mhammond** [comment]
huh - that's very odd! Sadly the output has scrolled away, but I swear it said everything was good (it's fairly obvious when it's not). But yeah, `-check` now says the same thing, and if I re-run it, everything seems to work. So 🤷

**Comment by LincolnPuzey** [comment]
I was able to reproduce the invalid formatting you got the first time by checking out `master` branch and running `black --fast .`

After that, running `black --check --diff --verbose --fast .` reports errors in the same 3 files the action did before.

However running `black .` on `master` produces code that passes black.

<hr/>

So I'm guessing there's a bug in black when the `--fast` flag is used. Which is strange because as far as I know, the `--fast` flag disables the before-and-after AST equivalence check black does when reformatting, so shouldn't effect the actual output...

But now that think about it - I don't know what black does when the AST check detects a difference - so maybe the flag would effect the output.

I'll see if I can get together a minimal example to report a bug

<hr/>

Regardless, I think its OK to use `--fast` in the CI when just checking, but I wouldn't use it when actually reformatting.

**Review by LincolnPuzey — APPROVED** [review]
Anyway it looks good to me 👍

**Comment by mhammond** [comment]
> So I'm guessing there's a bug in black when the `--fast` flag is used

That's very odd, because I'm fairly sure I didn't actually use `--fast` and my shell history seems to agree! Regardless, I agree `--fast` seems fine for CI until it proves not to be :)

**Comment by mhammond** [comment]
Thanks!

**Pull request merged**
