### PR TITLE
Remove support for Python 2.x

### PR DESCRIPTION
**Pull request by mhammond**
I'm going to remove Python 2.x support, which will make things alot simpler. There are still lots of places that do, eg, `sys.version_info < (3,)` and I might get to some of these or I might not - it doesn't really matter if they hang around a bit longer.

### CODE REVIEW

**Comment by vernondcole** [comment]
This will surely make things easier, but I was expecting one last bug fix release before dropping 2.7 altogether.  The adodbapi code, especially the documentation, could use some cleanup before release. I had to keep some ugly things in place for backwards compatibility reasons, and I can get rid of those now. How much time to I have to make things pretty?

**Comment by mhammond** [comment]
I can still make a release before landing this - what significant bugs since 227 make this worthwhile?

Re making things pretty, I'm not sure if you mean "how long between killing py2 and the next release"? If so, I'm fairly flexible :) Feel free to push relevant changes to this branch if you want, then all such cleanups could land at the same time.

**Comment by vernondcole** [comment]
My day job is really getting in the way here. I finally found time to spin
up a new Windows VM to check for sure what I thought I remembered.

The current version does not have the fix to make "install adodbapi" work.
Let's publish that fix before writing 2.7 off as an obsolete thing. (And
what a fine day that will be.)

**Comment by mhammond** [comment]
@vernondcole I've updated this branch and split some of the commits - the ones which change adodbapi are now in their own commits to make it easier for you to review. It would be great if you can have a look. I'm hoping to merge this within the next week or so, but don't currently have plans to make a release - so there will still be some time after merging this to update other things, such as docs etc. Let me know what you think.

**Comment by kxrob** [comment]
the  `execfile ` 2to3 is still missing: #1539  - error with PYTHONSTARTUP set.

**Pull request merged**
